addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 907169e1-6f9f-4ace-81ab-2258232de425
after_success:
- ./df-build.sh
before_install:
- curl -L --cookie 'oraclelicense=accept-securebackup-cookie;'  http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
  -o /tmp/policy.zip && sudo unzip -j -o /tmp/policy.zip *.jar -d `jdk_switcher home
  oraclejdk8`/jre/lib/security && rm /tmp/policy.zip
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-prod1.public-swarm.devfactory.com/travisWebHookListener?build_id=907169e1-6f9f-4ace-81ab-2258232de425
script:
- mvn apache-rat:check
- mvn clean test package
- jdk_switcher use oraclejdk7
- mvn verify site
- jdk_switcher use oraclejdk8
- mvn verify site
# Modified by Insights Service at 2016-10-16 21:54:52.578551
